'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17348
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace ContentService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="mtpsFaultDetailType", [Namespace]:="urn:msdn-com:public-content-syndication"),  _
     System.SerializableAttribute()>  _
    Partial Public Class mtpsFaultDetailType
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private eventIdField As String
        
        Private sourceField As String
        
        Private helpLinkField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false)>  _
        Public Property eventId() As String
            Get
                Return Me.eventIdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.eventIdField, value) <> true) Then
                    Me.eventIdField = value
                    Me.RaisePropertyChanged("eventId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false)>  _
        Public Property source() As String
            Get
                Return Me.sourceField
            End Get
            Set
                If (Object.ReferenceEquals(Me.sourceField, value) <> true) Then
                    Me.sourceField = value
                    Me.RaisePropertyChanged("source")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false, Order:=2)>  _
        Public Property helpLink() As String
            Get
                Return Me.helpLinkField
            End Get
            Set
                If (Object.ReferenceEquals(Me.helpLinkField, value) <> true) Then
                    Me.helpLinkField = value
                    Me.RaisePropertyChanged("helpLink")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="urn:msdn-com:public-content-syndication", ConfigurationName:="ContentService.ContentServicePortType")>  _
    Public Interface ContentServicePortType
        
        'CODEGEN: Generating message contract since the operation GetContent is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="urn:msdn-com:public-content-syndication/GetContent", ReplyAction:="*"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ContentService.mtpsFaultDetailType), Action:="urn:msdn-com:public-content-syndication/GetContent", Name:="mtpsFaultDetail"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(requestedDocument())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(primary())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(image())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(common())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(feature()))>  _
        Function GetContent(ByVal request As ContentService.GetContentRequest1) As ContentService.GetContentResponse1
        
        'CODEGEN: Generating message contract since the operation GetNavigationPaths is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="urn:msdn-com:public-content-syndication/GetNavigationPaths", ReplyAction:="*"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ContentService.mtpsFaultDetailType), Action:="urn:msdn-com:public-content-syndication/GetNavigationPaths", Name:="mtpsFaultDetail"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(requestedDocument())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(primary())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(image())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(common())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(feature()))>  _
        Function GetNavigationPaths(ByVal request As ContentService.GetNavigationPathsRequest1) As ContentService.GetNavigationPathsResponse1
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17348"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:msdn-com:public-content-syndication/2006/09/common")>  _
    Partial Public Class appId
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private valueField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property value() As String
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
                Me.RaisePropertyChanged("value")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17348"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:msdn-com:public-content-syndication")>  _
    Partial Public Class navigationPathNode
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private titleField As String
        
        Private isPhantomField As Boolean
        
        Private isPhantomFieldSpecified As Boolean
        
        Private navigationNodeKeyField As navigationKey
        
        Private contentNodeKeyField As navigationKey
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property title() As String
            Get
                Return Me.titleField
            End Get
            Set
                Me.titleField = value
                Me.RaisePropertyChanged("title")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property isPhantom() As Boolean
            Get
                Return Me.isPhantomField
            End Get
            Set
                Me.isPhantomField = value
                Me.RaisePropertyChanged("isPhantom")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property isPhantomSpecified() As Boolean
            Get
                Return Me.isPhantomFieldSpecified
            End Get
            Set
                Me.isPhantomFieldSpecified = value
                Me.RaisePropertyChanged("isPhantomSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property navigationNodeKey() As navigationKey
            Get
                Return Me.navigationNodeKeyField
            End Get
            Set
                Me.navigationNodeKeyField = value
                Me.RaisePropertyChanged("navigationNodeKey")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property contentNodeKey() As navigationKey
            Get
                Return Me.contentNodeKeyField
            End Get
            Set
                Me.contentNodeKeyField = value
                Me.RaisePropertyChanged("contentNodeKey")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17348"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:msdn-com:public-content-syndication")>  _
    Partial Public Class navigationKey
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private contentIdField As String
        
        Private localeField As String
        
        Private versionField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="urn:mtpg-com:mtps/2004/1/key", Order:=0)>  _
        Public Property contentId() As String
            Get
                Return Me.contentIdField
            End Get
            Set
                Me.contentIdField = value
                Me.RaisePropertyChanged("contentId")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="urn:mtpg-com:mtps/2004/1/key", Order:=1)>  _
        Public Property locale() As String
            Get
                Return Me.localeField
            End Get
            Set
                Me.localeField = value
                Me.RaisePropertyChanged("locale")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="urn:mtpg-com:mtps/2004/1/key", Order:=2)>  _
        Public Property version() As String
            Get
                Return Me.versionField
            End Get
            Set
                Me.versionField = value
                Me.RaisePropertyChanged("version")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17348"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:msdn-com:public-content-syndication")>  _
    Partial Public Class navigationPath
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private navigationPathNodesField() As navigationPathNode
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Order:=0),  _
         System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property navigationPathNodes() As navigationPathNode()
            Get
                Return Me.navigationPathNodesField
            End Get
            Set
                Me.navigationPathNodesField = value
                Me.RaisePropertyChanged("navigationPathNodes")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17348"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:msdn-com:public-content-syndication")>  _
    Partial Public Class availableVersionAndLocale
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private localeField As String
        
        Private versionField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="urn:mtpg-com:mtps/2004/1/key", Order:=0)>  _
        Public Property locale() As String
            Get
                Return Me.localeField
            End Get
            Set
                Me.localeField = value
                Me.RaisePropertyChanged("locale")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="urn:mtpg-com:mtps/2004/1/key", Order:=1)>  _
        Public Property version() As String
            Get
                Return Me.versionField
            End Get
            Set
                Me.versionField = value
                Me.RaisePropertyChanged("version")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17348"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:msdn-com:public-content-syndication")>  _
    Partial Public Class requestedDocument
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private selectorField As String
        
        Private typeField As documentTypes
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property selector() As String
            Get
                Return Me.selectorField
            End Get
            Set
                Me.selectorField = value
                Me.RaisePropertyChanged("selector")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property type() As documentTypes
            Get
                Return Me.typeField
            End Get
            Set
                Me.typeField = value
                Me.RaisePropertyChanged("type")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17348"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:msdn-com:public-content-syndication")>  _
    Public Enum documentTypes
        
        '''<remarks/>
        primary
        
        '''<remarks/>
        common
        
        '''<remarks/>
        image
        
        '''<remarks/>
        feature
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17348"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:mtpg-com:mtps/2004/1/primary")>  _
    Partial Public Class primary
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private anyField As System.Xml.XmlElement
        
        Private primaryFormatField As String
        
        Private locationField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute(Order:=0)>  _
        Public Property Any() As System.Xml.XmlElement
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = value
                Me.RaisePropertyChanged("Any")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Qualified, [Namespace]:="urn:mtpg-com:mtps/2004/1/primary/category")>  _
        Public Property primaryFormat() As String
            Get
                Return Me.primaryFormatField
            End Get
            Set
                Me.primaryFormatField = value
                Me.RaisePropertyChanged("primaryFormat")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property location() As String
            Get
                Return Me.locationField
            End Get
            Set
                Me.locationField = value
                Me.RaisePropertyChanged("location")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17348"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:mtpg-com:mtps/2004/1/image")>  _
    Partial Public Class image
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private nameField As String
        
        Private imageFormatField As String
        
        Private locationField As String
        
        Private valueField() As Byte
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
                Me.RaisePropertyChanged("name")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Qualified, [Namespace]:="urn:mtpg-com:mtps/2004/1/image/category")>  _
        Public Property imageFormat() As String
            Get
                Return Me.imageFormatField
            End Get
            Set
                Me.imageFormatField = value
                Me.RaisePropertyChanged("imageFormat")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property location() As String
            Get
                Return Me.locationField
            End Get
            Set
                Me.locationField = value
                Me.RaisePropertyChanged("location")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute(DataType:="base64Binary")>  _
        Public Property Value() As Byte()
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
                Me.RaisePropertyChanged("Value")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17348"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:mtpg-com:mtps/2004/1/common")>  _
    Partial Public Class common
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private anyField() As System.Xml.XmlElement
        
        Private commonFormatField As String
        
        Private locationField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute(Order:=0)>  _
        Public Property Any() As System.Xml.XmlElement()
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = value
                Me.RaisePropertyChanged("Any")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Qualified, [Namespace]:="urn:mtpg-com:mtps/2004/1/common/category")>  _
        Public Property commonFormat() As String
            Get
                Return Me.commonFormatField
            End Get
            Set
                Me.commonFormatField = value
                Me.RaisePropertyChanged("commonFormat")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property location() As String
            Get
                Return Me.locationField
            End Get
            Set
                Me.locationField = value
                Me.RaisePropertyChanged("location")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17348"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:mtpg-com:mtps/2004/1/feature")>  _
    Partial Public Class feature
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private anyField() As System.Xml.XmlElement
        
        Private featureFormatField As String
        
        Private locationField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute(Order:=0)>  _
        Public Property Any() As System.Xml.XmlElement()
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = value
                Me.RaisePropertyChanged("Any")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Qualified, [Namespace]:="urn:mtpg-com:mtps/2004/1/feature/category")>  _
        Public Property featureFormat() As String
            Get
                Return Me.featureFormatField
            End Get
            Set
                Me.featureFormatField = value
                Me.RaisePropertyChanged("featureFormat")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property location() As String
            Get
                Return Me.locationField
            End Get
            Set
                Me.locationField = value
                Me.RaisePropertyChanged("location")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17348"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:msdn-com:public-content-syndication")>  _
    Partial Public Class getContentRequest
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private contentIdentifierField As String
        
        Private localeField As String
        
        Private versionField As String
        
        Private requestedDocumentsField() As requestedDocument
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property contentIdentifier() As String
            Get
                Return Me.contentIdentifierField
            End Get
            Set
                Me.contentIdentifierField = value
                Me.RaisePropertyChanged("contentIdentifier")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="urn:mtpg-com:mtps/2004/1/key", Order:=1)>  _
        Public Property locale() As String
            Get
                Return Me.localeField
            End Get
            Set
                Me.localeField = value
                Me.RaisePropertyChanged("locale")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="urn:mtpg-com:mtps/2004/1/key", Order:=2)>  _
        Public Property version() As String
            Get
                Return Me.versionField
            End Get
            Set
                Me.versionField = value
                Me.RaisePropertyChanged("version")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Order:=3),  _
         System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property requestedDocuments() As requestedDocument()
            Get
                Return Me.requestedDocumentsField
            End Get
            Set
                Me.requestedDocumentsField = value
                Me.RaisePropertyChanged("requestedDocuments")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17348"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:msdn-com:public-content-syndication")>  _
    Partial Public Class getContentResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private contentIdField As String
        
        Private contentGuidField As String
        
        Private contentAliasField As String
        
        Private localeField As String
        
        Private versionField As String
        
        Private availableVersionsAndLocalesField() As availableVersionAndLocale
        
        Private primaryDocumentsField() As primary
        
        Private imageDocumentsField() As image
        
        Private commonDocumentsField() As common
        
        Private featureDocumentsField() As feature
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="urn:mtpg-com:mtps/2004/1/key", Order:=0)>  _
        Public Property contentId() As String
            Get
                Return Me.contentIdField
            End Get
            Set
                Me.contentIdField = value
                Me.RaisePropertyChanged("contentId")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="urn:mtpg-com:mtps/2004/1/key", Order:=1)>  _
        Public Property contentGuid() As String
            Get
                Return Me.contentGuidField
            End Get
            Set
                Me.contentGuidField = value
                Me.RaisePropertyChanged("contentGuid")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="urn:mtpg-com:mtps/2004/1/key", Order:=2)>  _
        Public Property contentAlias() As String
            Get
                Return Me.contentAliasField
            End Get
            Set
                Me.contentAliasField = value
                Me.RaisePropertyChanged("contentAlias")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="urn:mtpg-com:mtps/2004/1/key", Order:=3)>  _
        Public Property locale() As String
            Get
                Return Me.localeField
            End Get
            Set
                Me.localeField = value
                Me.RaisePropertyChanged("locale")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="urn:mtpg-com:mtps/2004/1/key", Order:=4)>  _
        Public Property version() As String
            Get
                Return Me.versionField
            End Get
            Set
                Me.versionField = value
                Me.RaisePropertyChanged("version")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Order:=5),  _
         System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property availableVersionsAndLocales() As availableVersionAndLocale()
            Get
                Return Me.availableVersionsAndLocalesField
            End Get
            Set
                Me.availableVersionsAndLocalesField = value
                Me.RaisePropertyChanged("availableVersionsAndLocales")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Order:=6),  _
         System.Xml.Serialization.XmlArrayItemAttribute("primary", [Namespace]:="urn:mtpg-com:mtps/2004/1/primary", IsNullable:=false)>  _
        Public Property primaryDocuments() As primary()
            Get
                Return Me.primaryDocumentsField
            End Get
            Set
                Me.primaryDocumentsField = value
                Me.RaisePropertyChanged("primaryDocuments")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Order:=7),  _
         System.Xml.Serialization.XmlArrayItemAttribute("image", [Namespace]:="urn:mtpg-com:mtps/2004/1/image", IsNullable:=false)>  _
        Public Property imageDocuments() As image()
            Get
                Return Me.imageDocumentsField
            End Get
            Set
                Me.imageDocumentsField = value
                Me.RaisePropertyChanged("imageDocuments")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Order:=8),  _
         System.Xml.Serialization.XmlArrayItemAttribute("common", [Namespace]:="urn:mtpg-com:mtps/2004/1/common", IsNullable:=false)>  _
        Public Property commonDocuments() As common()
            Get
                Return Me.commonDocumentsField
            End Get
            Set
                Me.commonDocumentsField = value
                Me.RaisePropertyChanged("commonDocuments")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Order:=9),  _
         System.Xml.Serialization.XmlArrayItemAttribute("feature", [Namespace]:="urn:mtpg-com:mtps/2004/1/feature", IsNullable:=false)>  _
        Public Property featureDocuments() As feature()
            Get
                Return Me.featureDocumentsField
            End Get
            Set
                Me.featureDocumentsField = value
                Me.RaisePropertyChanged("featureDocuments")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetContentRequest1
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="urn:msdn-com:public-content-syndication/2006/09/common")>  _
        Public appId As ContentService.appId
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:msdn-com:public-content-syndication", Order:=0)>  _
        Public getContentRequest As ContentService.getContentRequest
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal appId As ContentService.appId, ByVal getContentRequest As ContentService.getContentRequest)
            MyBase.New
            Me.appId = appId
            Me.getContentRequest = getContentRequest
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetContentResponse1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:msdn-com:public-content-syndication", Order:=0)>  _
        Public getContentResponse As ContentService.getContentResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal getContentResponse As ContentService.getContentResponse)
            MyBase.New
            Me.getContentResponse = getContentResponse
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17348"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:msdn-com:public-content-syndication")>  _
    Partial Public Class getNavigationPathsRequest
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private rootField As navigationKey
        
        Private targetField As navigationKey
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property root() As navigationKey
            Get
                Return Me.rootField
            End Get
            Set
                Me.rootField = value
                Me.RaisePropertyChanged("root")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property target() As navigationKey
            Get
                Return Me.targetField
            End Get
            Set
                Me.targetField = value
                Me.RaisePropertyChanged("target")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17348"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:msdn-com:public-content-syndication")>  _
    Partial Public Class getNavigationPathsResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private navigationPathsField() As navigationPath
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Order:=0),  _
         System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property navigationPaths() As navigationPath()
            Get
                Return Me.navigationPathsField
            End Get
            Set
                Me.navigationPathsField = value
                Me.RaisePropertyChanged("navigationPaths")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetNavigationPathsRequest1
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="urn:msdn-com:public-content-syndication/2006/09/common")>  _
        Public appId As ContentService.appId
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:msdn-com:public-content-syndication", Order:=0)>  _
        Public getNavigationPathsRequest As ContentService.getNavigationPathsRequest
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal appId As ContentService.appId, ByVal getNavigationPathsRequest As ContentService.getNavigationPathsRequest)
            MyBase.New
            Me.appId = appId
            Me.getNavigationPathsRequest = getNavigationPathsRequest
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetNavigationPathsResponse1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:msdn-com:public-content-syndication", Order:=0)>  _
        Public getNavigationPathsResponse As ContentService.getNavigationPathsResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal getNavigationPathsResponse As ContentService.getNavigationPathsResponse)
            MyBase.New
            Me.getNavigationPathsResponse = getNavigationPathsResponse
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ContentServicePortTypeChannel
        Inherits ContentService.ContentServicePortType, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ContentServicePortTypeClient
        Inherits System.ServiceModel.ClientBase(Of ContentService.ContentServicePortType)
        Implements ContentService.ContentServicePortType
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ContentService_ContentServicePortType_GetContent(ByVal request As ContentService.GetContentRequest1) As ContentService.GetContentResponse1 Implements ContentService.ContentServicePortType.GetContent
            Return MyBase.Channel.GetContent(request)
        End Function
        
        Public Function GetContent(ByVal appId As ContentService.appId, ByVal getContentRequest As ContentService.getContentRequest) As ContentService.getContentResponse
            Dim inValue As ContentService.GetContentRequest1 = New ContentService.GetContentRequest1()
            inValue.appId = appId
            inValue.getContentRequest = getContentRequest
            Dim retVal As ContentService.GetContentResponse1 = CType(Me,ContentService.ContentServicePortType).GetContent(inValue)
            Return retVal.getContentResponse
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ContentService_ContentServicePortType_GetNavigationPaths(ByVal request As ContentService.GetNavigationPathsRequest1) As ContentService.GetNavigationPathsResponse1 Implements ContentService.ContentServicePortType.GetNavigationPaths
            Return MyBase.Channel.GetNavigationPaths(request)
        End Function
        
        Public Function GetNavigationPaths(ByVal appId As ContentService.appId, ByVal getNavigationPathsRequest As ContentService.getNavigationPathsRequest) As ContentService.getNavigationPathsResponse
            Dim inValue As ContentService.GetNavigationPathsRequest1 = New ContentService.GetNavigationPathsRequest1()
            inValue.appId = appId
            inValue.getNavigationPathsRequest = getNavigationPathsRequest
            Dim retVal As ContentService.GetNavigationPathsResponse1 = CType(Me,ContentService.ContentServicePortType).GetNavigationPaths(inValue)
            Return retVal.getNavigationPathsResponse
        End Function
    End Class
End Namespace
