id:
name: GitOps.PullRequestIssueManagement
description: GitOps.PullRequestIssueManagement primitive
owner:
resource: repository
disabled: true
where:
configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
    - description: Auto-merge PRs to live labeled with auto-merge
      triggerOnOwnActions: true
      if:
        - payloadType: Pull_Request
        - labelAdded:
            label: ':octocat: auto-merge'
        - targetsBranch:
            branch: live
        - isActivitySender:
            user: microsoft-github-policy-service[bot]
      then:
        - enableAutoMerge:
            mergeMethod: Merge

    - description: Don't auto-merge PRs with auto-merge label removed
      if:
        - payloadType: Pull_Request
        - labelRemoved:
            label: ':octocat: auto-merge'
      then:
        - disableAutoMerge
