//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.21026.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Trin_VstcoreProgrammingControlsExcelCS {
    
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.ComponentModel.ToolboxItemAttribute(false)]
    [global::System.ComponentModel.DefaultEventAttribute("Load")]
    [global::System.ComponentModel.DefaultPropertyAttribute("Text")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
    internal partial class Trin_VstcoreProgrammingControlsExcelCS_ChartOptions : Trin_VstcoreProgrammingControlsExcelCS.ChartOptions {
        
        public object Activate() {
            return ((Microsoft.Office.Tools.Excel.ControlSite)(this.extenderControl)).Activate();
        }
        
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public string AltHTML {
            get {
                return ((Microsoft.Office.Tools.Excel.ControlSite)(this.extenderControl)).AltHTML;
            }
            set {
                ((Microsoft.Office.Tools.Excel.ControlSite)(this.extenderControl)).AltHTML = value;
            }
        }
        
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public Microsoft.Office.Interop.Excel.Application Application {
            get {
                return ((Microsoft.Office.Tools.Excel.ControlSite)(this.extenderControl)).Application;
            }
        }
        
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public bool AutoLoad {
            get {
                return ((Microsoft.Office.Tools.Excel.ControlSite)(this.extenderControl)).AutoLoad;
            }
            set {
                ((Microsoft.Office.Tools.Excel.ControlSite)(this.extenderControl)).AutoLoad = value;
            }
        }
        
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public bool AutoUpdate {
            get {
                return ((Microsoft.Office.Tools.Excel.ControlSite)(this.extenderControl)).AutoUpdate;
            }
            set {
                ((Microsoft.Office.Tools.Excel.ControlSite)(this.extenderControl)).AutoUpdate = value;
            }
        }
        
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public Microsoft.Office.Interop.Excel.Border Border {
            get {
                return ((Microsoft.Office.Tools.Excel.ControlSite)(this.extenderControl)).Border;
            }
        }
        
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public Microsoft.Office.Interop.Excel.Range BottomRightCell {
            get {
                return ((Microsoft.Office.Tools.Excel.ControlSite)(this.extenderControl)).BottomRightCell;
            }
        }
        
        public new object BringToFront() {
            return ((Microsoft.Office.Tools.Excel.ControlSite)(this.extenderControl)).BringToFront();
        }
        
        public object Copy() {
            return ((Microsoft.Office.Tools.Excel.ControlSite)(this.extenderControl)).Copy();
        }
        
        public object CopyPicture(Microsoft.Office.Interop.Excel.XlPictureAppearance Appearance, Microsoft.Office.Interop.Excel.XlCopyPictureFormat Format) {
            return ((Microsoft.Office.Tools.Excel.ControlSite)(this.extenderControl)).CopyPicture(Appearance, Format);
        }
        
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public Microsoft.Office.Interop.Excel.XlCreator Creator {
            get {
                return ((Microsoft.Office.Tools.Excel.ControlSite)(this.extenderControl)).Creator;
            }
        }
        
        public object Cut() {
            return ((Microsoft.Office.Tools.Excel.ControlSite)(this.extenderControl)).Cut();
        }
        
        public object Delete() {
            return ((Microsoft.Office.Tools.Excel.ControlSite)(this.extenderControl)).Delete();
        }
        
        public object Duplicate() {
            return ((Microsoft.Office.Tools.Excel.ControlSite)(this.extenderControl)).Duplicate();
        }
        
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new double Height {
            get {
                return ((Microsoft.Office.Tools.Excel.ControlSite)(this.extenderControl)).Height;
            }
            set {
                ((Microsoft.Office.Tools.Excel.ControlSite)(this.extenderControl)).Height = value;
            }
        }
        
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public int Index {
            get {
                return ((Microsoft.Office.Tools.Excel.ControlSite)(this.extenderControl)).Index;
            }
        }
        
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public Microsoft.Office.Interop.Excel.Interior Interior {
            get {
                return ((Microsoft.Office.Tools.Excel.ControlSite)(this.extenderControl)).Interior;
            }
        }
        
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new double Left {
            get {
                return ((Microsoft.Office.Tools.Excel.ControlSite)(this.extenderControl)).Left;
            }
            set {
                ((Microsoft.Office.Tools.Excel.ControlSite)(this.extenderControl)).Left = value;
            }
        }
        
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public string LinkedCell {
            get {
                return ((Microsoft.Office.Tools.Excel.ControlSite)(this.extenderControl)).LinkedCell;
            }
            set {
                ((Microsoft.Office.Tools.Excel.ControlSite)(this.extenderControl)).LinkedCell = value;
            }
        }
        
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public string ListFillRange {
            get {
                return ((Microsoft.Office.Tools.Excel.ControlSite)(this.extenderControl)).ListFillRange;
            }
            set {
                ((Microsoft.Office.Tools.Excel.ControlSite)(this.extenderControl)).ListFillRange = value;
            }
        }
        
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public bool Locked {
            get {
                return ((Microsoft.Office.Tools.Excel.ControlSite)(this.extenderControl)).Locked;
            }
            set {
                ((Microsoft.Office.Tools.Excel.ControlSite)(this.extenderControl)).Locked = value;
            }
        }
        
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public object OLEType {
            get {
                return ((Microsoft.Office.Tools.Excel.ControlSite)(this.extenderControl)).OLEType;
            }
        }
        
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public object Object {
            get {
                return ((Microsoft.Office.Tools.Excel.ControlSite)(this.extenderControl)).Object;
            }
        }
        
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public string OnAction {
            get {
                return ((Microsoft.Office.Tools.Excel.ControlSite)(this.extenderControl)).OnAction;
            }
            set {
                ((Microsoft.Office.Tools.Excel.ControlSite)(this.extenderControl)).OnAction = value;
            }
        }
        
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new object Parent {
            get {
                return ((Microsoft.Office.Tools.Excel.ControlSite)(this.extenderControl)).Parent;
            }
        }
        
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public object Placement {
            get {
                return ((Microsoft.Office.Tools.Excel.ControlSite)(this.extenderControl)).Placement;
            }
            set {
                ((Microsoft.Office.Tools.Excel.ControlSite)(this.extenderControl)).Placement = value;
            }
        }
        
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public bool PrintObject {
            get {
                return ((Microsoft.Office.Tools.Excel.ControlSite)(this.extenderControl)).PrintObject;
            }
            set {
                ((Microsoft.Office.Tools.Excel.ControlSite)(this.extenderControl)).PrintObject = value;
            }
        }
        
        public object Select(object Replace) {
            return ((Microsoft.Office.Tools.Excel.ControlSite)(this.extenderControl)).Select(Replace);
        }
        
        public new object SendToBack() {
            return ((Microsoft.Office.Tools.Excel.ControlSite)(this.extenderControl)).SendToBack();
        }
        
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public bool Shadow {
            get {
                return ((Microsoft.Office.Tools.Excel.ControlSite)(this.extenderControl)).Shadow;
            }
            set {
                ((Microsoft.Office.Tools.Excel.ControlSite)(this.extenderControl)).Shadow = value;
            }
        }
        
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public Microsoft.Office.Interop.Excel.ShapeRange ShapeRange {
            get {
                return ((Microsoft.Office.Tools.Excel.ControlSite)(this.extenderControl)).ShapeRange;
            }
        }
        
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public string SourceName {
            get {
                return ((Microsoft.Office.Tools.Excel.ControlSite)(this.extenderControl)).SourceName;
            }
            set {
                ((Microsoft.Office.Tools.Excel.ControlSite)(this.extenderControl)).SourceName = value;
            }
        }
        
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new double Top {
            get {
                return ((Microsoft.Office.Tools.Excel.ControlSite)(this.extenderControl)).Top;
            }
            set {
                ((Microsoft.Office.Tools.Excel.ControlSite)(this.extenderControl)).Top = value;
            }
        }
        
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public Microsoft.Office.Interop.Excel.Range TopLeftCell {
            get {
                return ((Microsoft.Office.Tools.Excel.ControlSite)(this.extenderControl)).TopLeftCell;
            }
        }
        
        public new object Update() {
            return ((Microsoft.Office.Tools.Excel.ControlSite)(this.extenderControl)).Update();
        }
        
        public object Verb(Microsoft.Office.Interop.Excel.XlOLEVerb VerbArgument) {
            return ((Microsoft.Office.Tools.Excel.ControlSite)(this.extenderControl)).Verb(VerbArgument);
        }
        
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new bool Visible {
            get {
                return ((Microsoft.Office.Tools.Excel.ControlSite)(this.extenderControl)).Visible;
            }
            set {
                ((Microsoft.Office.Tools.Excel.ControlSite)(this.extenderControl)).Visible = value;
            }
        }
        
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new double Width {
            get {
                return ((Microsoft.Office.Tools.Excel.ControlSite)(this.extenderControl)).Width;
            }
            set {
                ((Microsoft.Office.Tools.Excel.ControlSite)(this.extenderControl)).Width = value;
            }
        }
        
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public int ZOrder {
            get {
                return ((Microsoft.Office.Tools.Excel.ControlSite)(this.extenderControl)).ZOrder;
            }
        }
        
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public string progID {
            get {
                return ((Microsoft.Office.Tools.Excel.ControlSite)(this.extenderControl)).progID;
            }
        }
        
        /// 
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Trin_VstcoreProgrammingControlsExcelCS_ChartOptions() {
        }
        
        /// 
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Trin_VstcoreProgrammingControlsExcelCS_ChartOptions(global::Microsoft.Office.Tools.Excel.Factory factory, global::Microsoft.Office.Tools.IHostItemProvider hostItemProvider, global::System.IServiceProvider serviceProvider, string cookie, string extenderCookie, object container, string identifier) {
            this.extenderControl = factory.CreateControlSite(serviceProvider, hostItemProvider, cookie, identifier, container, this);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void Dispose(bool disposing) {
            try {
                if ((disposing == true)) {
                    if ((this.extenderControl != null)) {
                        extenderControl.Dispose();
                    }
                }
            }
            catch (System.Exception ) {
            }
            finally {
                extenderControl = null;
                base.Dispose(disposing);
            }
        }
        
        private Microsoft.Office.Tools.Excel.ControlSite extenderControl;
    }
}
