'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17348
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''
<Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(1), _
 Global.System.Security.Permissions.PermissionSetAttribute(Global.System.Security.Permissions.SecurityAction.Demand, Name:="FullTrust")> _
Partial Public NotInheritable Class Sheet1
    Inherits Microsoft.Office.Tools.Excel.WorksheetBase

    Friend WithEvents NamedRange1 As Microsoft.Office.Tools.Excel.NamedRange

    Friend WithEvents CustomerIDNamedRange As Microsoft.Office.Tools.Excel.NamedRange

    Friend WithEvents CompanyNameNamedRange As Microsoft.Office.Tools.Excel.NamedRange

    Friend WithEvents Button1 As Microsoft.Office.Tools.Excel.Controls.Button

    Friend WithEvents Button2 As Microsoft.Office.Tools.Excel.Controls.Button

    Friend WithEvents Button3 As Microsoft.Office.Tools.Excel.Controls.Button

    Friend WithEvents Button4 As Microsoft.Office.Tools.Excel.Controls.Button

    Private components As System.ComponentModel.IContainer

    Friend WithEvents NorthwindDataSet As Trin_VstcoreDataExcelVB.NorthwindDataSet

    Friend WithEvents CustomersTableAdapter As Trin_VstcoreDataExcelVB.NorthwindDataSetTableAdapters.CustomersTableAdapter

    Friend WithEvents CustomersBindingSource As System.Windows.Forms.BindingSource

    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
    Public Sub New(ByVal factory As Global.Microsoft.Office.Tools.Excel.Factory, ByVal serviceProvider As Global.System.IServiceProvider)
        MyBase.New(factory, serviceProvider, "Sheet1", "Sheet1")
    End Sub

    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "11.0.0.0"), _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
    Protected Overrides Sub Initialize()
        MyBase.Initialize()
        Globals.Sheet1 = Me
        Global.System.Windows.Forms.Application.EnableVisualStyles()
        Me.InitializeCachedData()
        Me.InitializeControls()
        Me.InitializeComponents()
        Me.InitializeData()
    End Sub

    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "11.0.0.0"), _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
    Protected Overrides Sub FinishInitialization()
        Me.OnStartup()
    End Sub

    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "11.0.0.0"), _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
    Protected Overrides Sub InitializeDataBindings()
        Me.BeginInitialization()
        Me.BindToData()
        Me.EndInitialization()
    End Sub

    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "11.0.0.0"), _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
    Private Sub InitializeCachedData()
        If (Me.DataHost Is Nothing) Then
            Return
        End If
        If Me.DataHost.IsCacheInitialized Then
            Me.DataHost.FillCachedData(Me)
        End If
    End Sub

    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "11.0.0.0"), _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
    Private Sub InitializeData()
    End Sub

    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "11.0.0.0"), _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
    Private Sub BindToData()
        Me.CustomerIDNamedRange.DataBindings.Add("Value2", Me.CustomersBindingSource, "CustomerID", True, Me.CustomerIDNamedRange.DataBindings.DefaultDataSourceUpdateMode)
        Me.CompanyNameNamedRange.DataBindings.Add("Value2", Me.CustomersBindingSource, "CompanyName", True, Me.CompanyNameNamedRange.DataBindings.DefaultDataSourceUpdateMode)
    End Sub

    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Sub StartCaching(ByVal MemberName As String)
        Me.DataHost.StartCaching(Me, MemberName)
    End Sub

    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Sub StopCaching(ByVal MemberName As String)
        Me.DataHost.StopCaching(Me, MemberName)
    End Sub

    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Function IsCached(ByVal MemberName As String) As Boolean
        Return Me.DataHost.IsCached(Me, MemberName)
    End Function

    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "11.0.0.0"), _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
    Private Sub BeginInitialization()
        Me.BeginInit()
        Me.NamedRange1.BeginInit()
        Me.CustomerIDNamedRange.BeginInit()
        Me.CompanyNameNamedRange.BeginInit()
    End Sub

    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "11.0.0.0"), _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
    Private Sub EndInitialization()
        Me.CompanyNameNamedRange.EndInit()
        Me.CustomerIDNamedRange.EndInit()
        Me.NamedRange1.EndInit()
        Me.EndInit()
    End Sub

    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "11.0.0.0"), _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
    Private Sub InitializeControls()
        Me.NamedRange1 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "NamedRange1", "NamedRange1", Me)
        Me.CustomerIDNamedRange = Globals.Factory.CreateNamedRange(Nothing, Nothing, "CustomerIDNamedRange", "CustomerIDNamedRange", Me)
        Me.CompanyNameNamedRange = Globals.Factory.CreateNamedRange(Nothing, Nothing, "CompanyNameNamedRange", "CompanyNameNamedRange", Me)
        Me.Button1 = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "27DC915AF20570241C92A5A827ABAC50892602", "27DC915AF20570241C92A5A827ABAC50892602", Me, "Button1")
        Me.Button2 = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "328EA03B33214834EBD3A4593454A8B9BC33F3", "328EA03B33214834EBD3A4593454A8B9BC33F3", Me, "Button2")
        Me.Button3 = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "439237A8A4654B4402E4BFBC4820F9E94059B4", "439237A8A4654B4402E4BFBC4820F9E94059B4", Me, "Button3")
        Me.Button4 = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "5F8258DB752FD6543895B8CA579986F3A9C275", "5F8258DB752FD6543895B8CA579986F3A9C275", Me, "Button4")
    End Sub

    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "11.0.0.0"), _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
    Private Sub InitializeComponents()
        Me.components = New System.ComponentModel.Container()
        If (Me.NorthwindDataSet Is Nothing) Then
            'Instantiate the object if not yet loaded from the data cache.
            Me.NorthwindDataSet = New Trin_VstcoreDataExcelVB.NorthwindDataSet()
        End If
        Me.CustomersTableAdapter = New Trin_VstcoreDataExcelVB.NorthwindDataSetTableAdapters.CustomersTableAdapter()
        Me.CustomersBindingSource = New System.Windows.Forms.BindingSource(Me.components)
        CType(Me.NamedRange1, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.CustomerIDNamedRange, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.CompanyNameNamedRange, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.NorthwindDataSet, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.CustomersBindingSource, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me, System.ComponentModel.ISupportInitialize).BeginInit()
        '
        'Button1
        '
        Me.Button1.Name = "Button1"
        Me.Button1.Text = "Button1"
        '
        'Button2
        '
        Me.Button2.Name = "Button2"
        Me.Button2.Text = "Button2"
        '
        'Button3
        '
        Me.Button3.Name = "Button3"
        Me.Button3.Text = "Button3"
        '
        'Button4
        '
        Me.Button4.Name = "Button4"
        Me.Button4.Text = "Button4"
        '
        'NorthwindDataSet
        '
        Me.NorthwindDataSet.DataSetName = "NorthwindDataSet"
        '
        'CustomersTableAdapter
        '
        Me.CustomersTableAdapter.ClearBeforeFill = True
        '
        'CustomersBindingSource
        '
        Me.CustomersBindingSource.DataMember = "Customers"
        Me.CustomersBindingSource.DataSource = Me.NorthwindDataSet
        '
        'Sheet1
        '
        CType(Me.NamedRange1, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.CustomerIDNamedRange, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.CompanyNameNamedRange, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.NorthwindDataSet, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.CustomersBindingSource, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me, System.ComponentModel.ISupportInitialize).EndInit()
        Me.Button1.BindingContext = Me.BindingContext
        Me.Button2.BindingContext = Me.BindingContext
        Me.Button3.BindingContext = Me.BindingContext
        Me.Button4.BindingContext = Me.BindingContext
    End Sub

    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Function NeedsFill(ByVal MemberName As String) As Boolean
        Return Me.DataHost.NeedsFill(Me, MemberName)
    End Function

    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "11.0.0.0"), _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
    Protected Overrides Sub OnShutdown()
        Me.CompanyNameNamedRange.Dispose()
        Me.CustomerIDNamedRange.Dispose()
        Me.NamedRange1.Dispose()
        MyBase.OnShutdown()
    End Sub
End Class

Partial Friend NotInheritable Class Globals

    Private Shared _Sheet1 As Sheet1

    Friend Shared Property Sheet1() As Sheet1
        Get
            Return _Sheet1
        End Get
        Set(value As Sheet1)
            If (_Sheet1 Is Nothing) Then
                _Sheet1 = value
            Else
                Throw New System.NotSupportedException()
            End If
        End Set
    End Property
End Class
