//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.20529.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkflowImportProject1
{
    using System.Workflow.Activities;
    using System.Workflow.ComponentModel;
    using System.Workflow.Runtime;
    using Microsoft.SharePoint.WorkflowActions;
    //<Snippet1>
    using Microsoft.SharePoint;
    using System;
    //</Snippet1>
    
    public partial class SPD_Task_WorkflowFT : RootWorkflowActivityWithData
    {
        //<Snippet2>
        private void codeActivity1_ExecuteCode(object sender, System.EventArgs e)
        {
            
            try
            {
                // Get reference to SharePoint site.
                SPSite site = new SPSite("http://MyServer");
                SPWeb web = site.OpenWeb("SPD2/");
                // Get reference to Announcements list.
                SPList announcementsList = web.Lists["Announcements"];

                // Add announcement to Announcements list for the Task.
                SPListItem oListItem = announcementsList.Items.Add();
                oListItem["Title"] = "Assigned task on " + DateTime.Now.ToString();
                oListItem.Update();
            }

            catch (Exception err)
            {
                Console.WriteLine("Error: " + err.ToString());
            }        
        }
        //</Snippet2>
    }
}
