'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.21106.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On




<Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
 Global.System.ComponentModel.ToolboxItemAttribute(False), _
 Global.System.ComponentModel.DefaultEventAttribute("Load"), _
 Global.System.ComponentModel.DefaultPropertyAttribute("Text"), _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")> _
Partial Friend Class My_Chart_Options_ChartOptions
    Inherits My_Chart_Options.ChartOptions

    Public Sub Activate()
        CType(Me.extenderControl, Microsoft.Office.Tools.Word.ControlSite).Activate()
    End Sub

    <Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)> _
    Public Property AltHTML() As String
        Get
            Return CType(Me.extenderControl, Microsoft.Office.Tools.Word.ControlSite).AltHTML
        End Get
        Set(ByVal value As String)
            CType(Me.extenderControl, Microsoft.Office.Tools.Word.ControlSite).AltHTML = value
        End Set
    End Property

    <Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)> _
    Public ReadOnly Property Automation() As Object
        Get
            Return CType(Me.extenderControl, Microsoft.Office.Tools.Word.ControlSite).Automation
        End Get
    End Property

    Public Sub Copy()
        CType(Me.extenderControl, Microsoft.Office.Tools.Word.ControlSite).Copy()
    End Sub

    Public Sub Cut()
        CType(Me.extenderControl, Microsoft.Office.Tools.Word.ControlSite).Cut()
    End Sub

    Public Sub Delete()
        CType(Me.extenderControl, Microsoft.Office.Tools.Word.ControlSite).Delete()
    End Sub

    <Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)> _
    Public Shadows Property Height() As Single
        Get
            Return CType(Me.extenderControl, Microsoft.Office.Tools.Word.ControlSite).Height
        End Get
        Set(ByVal value As Single)
            CType(Me.extenderControl, Microsoft.Office.Tools.Word.ControlSite).Height = value
        End Set
    End Property

    <Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)> _
    Public ReadOnly Property InlineShape() As Microsoft.Office.Interop.Word.InlineShape
        Get
            Return CType(Me.extenderControl, Microsoft.Office.Tools.Word.ControlSite).InlineShape
        End Get
    End Property

    <Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)> _
    Public Shadows Property Left() As Single
        Get
            Return CType(Me.extenderControl, Microsoft.Office.Tools.Word.ControlSite).Left
        End Get
        Set(ByVal value As Single)
            CType(Me.extenderControl, Microsoft.Office.Tools.Word.ControlSite).Left = value
        End Set
    End Property

    Public Shadows Sub [Select]()
        CType(Me.extenderControl, Microsoft.Office.Tools.Word.ControlSite).Select()
    End Sub

    <Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)> _
    Public ReadOnly Property Shape() As Microsoft.Office.Interop.Word.Shape
        Get
            Return CType(Me.extenderControl, Microsoft.Office.Tools.Word.ControlSite).Shape
        End Get
    End Property

    <Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)> _
    Public Shadows Property Top() As Single
        Get
            Return CType(Me.extenderControl, Microsoft.Office.Tools.Word.ControlSite).Top
        End Get
        Set(ByVal value As Single)
            CType(Me.extenderControl, Microsoft.Office.Tools.Word.ControlSite).Top = value
        End Set
    End Property

    <Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)> _
    Public Shadows Property Width() As Single
        Get
            Return CType(Me.extenderControl, Microsoft.Office.Tools.Word.ControlSite).Width
        End Get
        Set(ByVal value As Single)
            CType(Me.extenderControl, Microsoft.Office.Tools.Word.ControlSite).Width = value
        End Set
    End Property

    '''
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
    Public Sub New()
        MyBase.New()
    End Sub

    '''
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
    Public Sub New(ByVal factory As Global.Microsoft.Office.Tools.Word.Factory, ByVal hostItemProvider As Global.Microsoft.Office.Tools.IHostItemProvider, ByVal serviceProvider As Global.System.IServiceProvider, ByVal cookie As String, ByVal extenderCookie As String, ByVal container As Object, ByVal identifier As String)
        MyBase.New()
        Me.extenderControl = factory.CreateControlSite(serviceProvider, hostItemProvider, cookie, identifier, container, Me)
    End Sub

    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0"), _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
    Protected Overrides Sub Dispose(ByVal disposing As Boolean)
        Try
            If (disposing = True) Then
                If (Not (Me.extenderControl) Is Nothing) Then
                    extenderControl.Dispose()
                End If
            End If
        Catch __exception As System.Exception
        Finally
            extenderControl = Nothing
            MyBase.Dispose(disposing)
        End Try
    End Sub

    Private extenderControl As Microsoft.Office.Tools.Word.ControlSite
End Class
