'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17348
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''
<Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(0), _
 Global.System.Security.Permissions.PermissionSetAttribute(Global.System.Security.Permissions.SecurityAction.Demand, Name:="FullTrust")> _
Partial Public NotInheritable Class ThisDocument
    Inherits Microsoft.Office.Tools.Word.DocumentBase

    Friend WithEvents ActionsPane As Microsoft.Office.Tools.ActionsPane

    Friend WithEvents fontText As Microsoft.Office.Tools.Word.Bookmark

    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "11.0.0.0")> _
    Friend WithEvents ThisApplication As Microsoft.Office.Interop.Word.Application

    Friend WithEvents ChartOptions1 As My_Chart_Options_ChartOptions

    Friend WithEvents applyBoldFont As Microsoft.Office.Tools.Word.Controls.CheckBox

    Friend WithEvents applyItalicFont As Microsoft.Office.Tools.Word.Controls.CheckBox

    Friend WithEvents applyUnderlineFont As Microsoft.Office.Tools.Word.Controls.CheckBox

    Friend WithEvents displayText As Microsoft.Office.Tools.Word.Controls.TextBox

    Friend WithEvents insertText As Microsoft.Office.Tools.Word.Controls.Button

    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
    Public Sub New(ByVal factory As Global.Microsoft.Office.Tools.Word.Factory, ByVal serviceProvider As Global.System.IServiceProvider)
        MyBase.New(factory, serviceProvider, "ThisDocument", "ThisDocument")
        Globals.Factory = factory
    End Sub

    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "11.0.0.0"), _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
    Protected Overrides Sub Initialize()
        MyBase.Initialize()
        Me.ThisApplication = Me.GetHostItem(Of Microsoft.Office.Interop.Word.Application)(GetType(Microsoft.Office.Interop.Word.Application), "Application")
        Globals.ThisDocument = Me
        Global.System.Windows.Forms.Application.EnableVisualStyles()
        Me.InitializeCachedData()
        Me.InitializeControls()
        Me.InitializeComponents()
        Me.InitializeData()
    End Sub

    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "11.0.0.0"), _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
    Protected Overrides Sub FinishInitialization()
        Me.OnStartup()
    End Sub

    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "11.0.0.0"), _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
    Protected Overrides Sub InitializeDataBindings()
        Me.BeginInitialization()
        Me.BindToData()
        Me.EndInitialization()
    End Sub

    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "11.0.0.0"), _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
    Private Sub InitializeCachedData()
        If (Me.DataHost Is Nothing) Then
            Return
        End If
        If Me.DataHost.IsCacheInitialized Then
            Me.DataHost.FillCachedData(Me)
        End If
    End Sub

    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "11.0.0.0"), _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
    Private Sub InitializeData()
    End Sub

    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "11.0.0.0"), _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
    Private Sub BindToData()
    End Sub

    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Sub StartCaching(ByVal MemberName As String)
        Me.DataHost.StartCaching(Me, MemberName)
    End Sub

    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Sub StopCaching(ByVal MemberName As String)
        Me.DataHost.StopCaching(Me, MemberName)
    End Sub

    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Function IsCached(ByVal MemberName As String) As Boolean
        Return Me.DataHost.IsCached(Me, MemberName)
    End Function

    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "11.0.0.0"), _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
    Private Sub BeginInitialization()
        Me.BeginInit()
        Me.ActionsPane.BeginInit()
        Me.fontText.BeginInit()
    End Sub

    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "11.0.0.0"), _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
    Private Sub EndInitialization()
        Me.fontText.EndInit()
        Me.ActionsPane.EndInit()
        Me.EndInit()
    End Sub

    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "11.0.0.0"), _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
    Private Sub InitializeControls()
        Me.ActionsPane = Globals.Factory.CreateActionsPane(Nothing, Nothing, "ActionsPane", "ActionsPane", Me)
        Me.fontText = Globals.Factory.CreateBookmark(Nothing, Nothing, "fontText", "fontText", Me)
        Me.ChartOptions1 = New My_Chart_Options_ChartOptions(Globals.Factory, Me.ItemProvider, Me.HostContext, "0333441530191E047AF090DD069A17B7101DC0", "0333441530191E047AF090DD069A17B7101DC0", Me, "ChartOptions1")
        Me.applyBoldFont = New Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, Me.ItemProvider, Me.HostContext, "10E44F4B0164A714C941B58C14B05C6393A6F1", "10E44F4B0164A714C941B58C14B05C6393A6F1", Me, "applyBoldFont")
        Me.applyItalicFont = New Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, Me.ItemProvider, Me.HostContext, "264E8E5D22930E2491B2AA6F249AE9F971C8C2", "264E8E5D22930E2491B2AA6F249AE9F971C8C2", Me, "applyItalicFont")
        Me.applyUnderlineFont = New Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, Me.ItemProvider, Me.HostContext, "366D5730D326753416D395233E8588E72EC733", "366D5730D326753416D395233E8588E72EC733", Me, "applyUnderlineFont")
        Me.displayText = New Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, Me.ItemProvider, Me.HostContext, "4E7785798459B444A424940D44E521BE4F1DD4", "4E7785798459B444A424940D44E521BE4F1DD4", Me, "displayText")
        Me.insertText = New Microsoft.Office.Tools.Word.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "5BE00FBB459C38548D0590C3584D1F18622CA5", "5BE00FBB459C38548D0590C3584D1F18622CA5", Me, "insertText")
    End Sub

    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "11.0.0.0"), _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
    Private Sub InitializeComponents()
        '
        'ActionsPane
        '
        Me.ActionsPane.AutoSize = False
        Me.ActionsPane.AutoValidate = System.Windows.Forms.AutoValidate.EnablePreventFocusChange
        '
        'ChartOptions1
        '
        Me.ChartOptions1.Name = "ChartOptions1"
        Me.ChartOptions1.Selection = Microsoft.Office.Interop.Graph.XlChartType.xlColumnClustered
        '
        'applyBoldFont
        '
        Me.applyBoldFont.Name = "applyBoldFont"
        Me.applyBoldFont.Text = "CheckBox1"
        '
        'applyItalicFont
        '
        Me.applyItalicFont.Name = "applyItalicFont"
        Me.applyItalicFont.Text = "CheckBox1"
        '
        'applyUnderlineFont
        '
        Me.applyUnderlineFont.Name = "applyUnderlineFont"
        Me.applyUnderlineFont.Text = "CheckBox1"
        '
        'fontText
        '
        Me.fontText.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'displayText
        '
        Me.displayText.Name = "displayText"
        Me.displayText.Text = "TextBox1"
        '
        'insertText
        '
        Me.insertText.BackColor = System.Drawing.SystemColors.Control
        Me.insertText.ForeColor = System.Drawing.SystemColors.ControlText
        Me.insertText.Name = "insertText"
        Me.insertText.Text = "Button1"
        Me.insertText.UseVisualStyleBackColor = False
        '
        'ThisDocument
        '
        Me.ChartOptions1.BindingContext = Me.BindingContext
        Me.applyBoldFont.BindingContext = Me.BindingContext
        Me.applyItalicFont.BindingContext = Me.BindingContext
        Me.applyUnderlineFont.BindingContext = Me.BindingContext
        Me.displayText.BindingContext = Me.BindingContext
        Me.insertText.BindingContext = Me.BindingContext
    End Sub

    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Function NeedsFill(ByVal MemberName As String) As Boolean
        Return Me.DataHost.NeedsFill(Me, MemberName)
    End Function

    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "11.0.0.0"), _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
    Protected Overrides Sub OnShutdown()
        Me.fontText.Dispose()
        Me.ActionsPane.Dispose()
        MyBase.OnShutdown()
    End Sub
End Class

'''
<Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "11.0.0.0")> _
Partial Friend NotInheritable Class Globals

    '''
    Private Sub New()
        MyBase.New()
    End Sub

    Private Shared _ThisDocument As ThisDocument

    Private Shared _factory As Global.Microsoft.Office.Tools.Word.Factory

    Private Shared _ThisRibbonCollection As ThisRibbonCollection

    Friend Shared Property ThisDocument() As ThisDocument
        Get
            Return _ThisDocument
        End Get
        Set(value As ThisDocument)
            If (_ThisDocument Is Nothing) Then
                _ThisDocument = value
            Else
                Throw New System.NotSupportedException()
            End If
        End Set
    End Property

    Friend Shared Property Factory() As Global.Microsoft.Office.Tools.Word.Factory
        Get
            Return _factory
        End Get
        Set(value As Global.Microsoft.Office.Tools.Word.Factory)
            If (_factory Is Nothing) Then
                _factory = value
            Else
                Throw New System.NotSupportedException()
            End If
        End Set
    End Property

    Friend Shared ReadOnly Property Ribbons() As ThisRibbonCollection
        Get
            If (_ThisRibbonCollection Is Nothing) Then
                _ThisRibbonCollection = New ThisRibbonCollection(_factory.GetRibbonFactory)
            End If
            Return _ThisRibbonCollection
        End Get
    End Property
End Class

'''
<Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "11.0.0.0")> _
Partial Friend NotInheritable Class ThisRibbonCollection
    Inherits Microsoft.Office.Tools.Ribbon.RibbonCollectionBase

    '''
    Friend Sub New(ByVal factory As Global.Microsoft.Office.Tools.Ribbon.RibbonFactory)
        MyBase.New(factory)
    End Sub
End Class
