'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30128.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


'Original file name:
'Generation date: 3/15/2010 1:57:55 PM
Namespace AdventureWorksService
    '''<summary>
    '''There are no comments for AdventureWorksLTEntities in the schema.
    '''</summary>
    Partial Public Class AdventureWorksLTEntities
        Inherits Global.System.Data.Services.Client.DataServiceContext
        '''<summary>
        '''Initialize a new AdventureWorksLTEntities object.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Sub New(ByVal serviceRoot As Global.System.Uri)
            MyBase.New(serviceRoot)
            Me.ResolveName = AddressOf Me.ResolveNameFromType
            Me.ResolveType = AddressOf Me.ResolveTypeFromName
            Me.OnContextCreated
        End Sub
        Partial Private Sub OnContextCreated()
        End Sub
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private Shared ROOTNAMESPACE As String = GetType(AdventureWorksService.AdventureWorksLTEntities).Namespace.Remove(GetType(AdventureWorksService.AdventureWorksLTEntities).Namespace.LastIndexOf("AdventureWorksService"))
        '''<summary>
        '''Since the namespace configured for this service reference
        '''in Visual Studio is different from the one indicated in the
        '''server schema, use type-mappers to map between the two.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Protected Function ResolveTypeFromName(ByVal typeName As String) As Global.System.Type
            If typeName.StartsWith("AdventureWorksLTModel", Global.System.StringComparison.OrdinalIgnoreCase) Then
                Return Me.GetType.Assembly.GetType(String.Concat(String.Concat(ROOTNAMESPACE, "AdventureWorksService"), typeName.Substring(21)), false)
            End If
            Return Nothing
        End Function
        '''<summary>
        '''Since the namespace configured for this service reference
        '''in Visual Studio is different from the one indicated in the
        '''server schema, use type-mappers to map between the two.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Protected Function ResolveNameFromType(ByVal clientType As Global.System.Type) As String
            If clientType.Namespace.Equals(String.Concat(ROOTNAMESPACE, "AdventureWorksService"), Global.System.StringComparison.OrdinalIgnoreCase) Then
                Return String.Concat("AdventureWorksLTModel.", clientType.Name)
            End If
            Return Nothing
        End Function
        '''<summary>
        '''There are no comments for SalesOrderHeaders in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public ReadOnly Property SalesOrderHeaders() As Global.System.Data.Services.Client.DataServiceQuery(Of SalesOrderHeader)
            Get
                If (Me._SalesOrderHeaders Is Nothing) Then
                    Me._SalesOrderHeaders = MyBase.CreateQuery(Of SalesOrderHeader)("SalesOrderHeaders")
                End If
                Return Me._SalesOrderHeaders
            End Get
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _SalesOrderHeaders As Global.System.Data.Services.Client.DataServiceQuery(Of SalesOrderHeader)
        '''<summary>
        '''There are no comments for SalesOrderHeaders in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Sub AddToSalesOrderHeaders(ByVal salesOrderHeader As SalesOrderHeader)
            MyBase.AddObject("SalesOrderHeaders", salesOrderHeader)
        End Sub
    End Class
    '''<summary>
    '''There are no comments for AdventureWorksLTModel.SalesOrderHeader in the schema.
    '''</summary>
    '''<KeyProperties>
    '''SalesOrderID
    '''</KeyProperties>
    <Global.System.Data.Services.Common.EntitySetAttribute("SalesOrderHeaders"),  _
     Global.System.Data.Services.Common.DataServiceKeyAttribute("SalesOrderID")>  _
    Partial Public Class SalesOrderHeader
        Implements Global.System.ComponentModel.INotifyPropertyChanged
        '''<summary>
        '''Create a new SalesOrderHeader object.
        '''</summary>
        '''<param name="salesOrderID">Initial value of SalesOrderID.</param>
        '''<param name="revisionNumber">Initial value of RevisionNumber.</param>
        '''<param name="orderDate">Initial value of OrderDate.</param>
        '''<param name="dueDate">Initial value of DueDate.</param>
        '''<param name="status">Initial value of Status.</param>
        '''<param name="onlineOrderFlag">Initial value of OnlineOrderFlag.</param>
        '''<param name="salesOrderNumber">Initial value of SalesOrderNumber.</param>
        '''<param name="customerID">Initial value of CustomerID.</param>
        '''<param name="shipMethod">Initial value of ShipMethod.</param>
        '''<param name="subTotal">Initial value of SubTotal.</param>
        '''<param name="taxAmt">Initial value of TaxAmt.</param>
        '''<param name="freight">Initial value of Freight.</param>
        '''<param name="totalDue">Initial value of TotalDue.</param>
        '''<param name="rowguid">Initial value of rowguid.</param>
        '''<param name="modifiedDate">Initial value of ModifiedDate.</param>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Shared Function CreateSalesOrderHeader(ByVal salesOrderID As Integer, ByVal revisionNumber As Byte, ByVal orderDate As Date, ByVal dueDate As Date, ByVal status As Byte, ByVal onlineOrderFlag As Boolean, ByVal salesOrderNumber As String, ByVal customerID As Integer, ByVal shipMethod As String, ByVal subTotal As Decimal, ByVal taxAmt As Decimal, ByVal freight As Decimal, ByVal totalDue As Decimal, ByVal rowguid As Global.System.Guid, ByVal modifiedDate As Date) As SalesOrderHeader
            Dim salesOrderHeader As SalesOrderHeader = New SalesOrderHeader()
            salesOrderHeader.SalesOrderID = salesOrderID
            salesOrderHeader.RevisionNumber = revisionNumber
            salesOrderHeader.OrderDate = orderDate
            salesOrderHeader.DueDate = dueDate
            salesOrderHeader.Status = status
            salesOrderHeader.OnlineOrderFlag = onlineOrderFlag
            salesOrderHeader.SalesOrderNumber = salesOrderNumber
            salesOrderHeader.CustomerID = customerID
            salesOrderHeader.ShipMethod = shipMethod
            salesOrderHeader.SubTotal = subTotal
            salesOrderHeader.TaxAmt = taxAmt
            salesOrderHeader.Freight = freight
            salesOrderHeader.TotalDue = totalDue
            salesOrderHeader.rowguid = rowguid
            salesOrderHeader.ModifiedDate = modifiedDate
            Return salesOrderHeader
        End Function
        '''<summary>
        '''There are no comments for Property SalesOrderID in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property SalesOrderID() As Integer
            Get
                Return Me._SalesOrderID
            End Get
            Set
                Me.OnSalesOrderIDChanging(value)
                Me._SalesOrderID = value
                Me.OnSalesOrderIDChanged
                Me.OnPropertyChanged("SalesOrderID")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _SalesOrderID As Integer
        Partial Private Sub OnSalesOrderIDChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub OnSalesOrderIDChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property RevisionNumber in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property RevisionNumber() As Byte
            Get
                Return Me._RevisionNumber
            End Get
            Set
                Me.OnRevisionNumberChanging(value)
                Me._RevisionNumber = value
                Me.OnRevisionNumberChanged
                Me.OnPropertyChanged("RevisionNumber")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _RevisionNumber As Byte
        Partial Private Sub OnRevisionNumberChanging(ByVal value As Byte)
        End Sub
        Partial Private Sub OnRevisionNumberChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property OrderDate in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property OrderDate() As Date
            Get
                Return Me._OrderDate
            End Get
            Set
                Me.OnOrderDateChanging(value)
                Me._OrderDate = value
                Me.OnOrderDateChanged
                Me.OnPropertyChanged("OrderDate")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _OrderDate As Date
        Partial Private Sub OnOrderDateChanging(ByVal value As Date)
        End Sub
        Partial Private Sub OnOrderDateChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property DueDate in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property DueDate() As Date
            Get
                Return Me._DueDate
            End Get
            Set
                Me.OnDueDateChanging(value)
                Me._DueDate = value
                Me.OnDueDateChanged
                Me.OnPropertyChanged("DueDate")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _DueDate As Date
        Partial Private Sub OnDueDateChanging(ByVal value As Date)
        End Sub
        Partial Private Sub OnDueDateChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property ShipDate in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ShipDate() As Global.System.Nullable(Of Date)
            Get
                Return Me._ShipDate
            End Get
            Set
                Me.OnShipDateChanging(value)
                Me._ShipDate = value
                Me.OnShipDateChanged
                Me.OnPropertyChanged("ShipDate")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ShipDate As Global.System.Nullable(Of Date)
        Partial Private Sub OnShipDateChanging(ByVal value As Global.System.Nullable(Of Date))
        End Sub
        Partial Private Sub OnShipDateChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Status in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Status() As Byte
            Get
                Return Me._Status
            End Get
            Set
                Me.OnStatusChanging(value)
                Me._Status = value
                Me.OnStatusChanged
                Me.OnPropertyChanged("Status")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Status As Byte
        Partial Private Sub OnStatusChanging(ByVal value As Byte)
        End Sub
        Partial Private Sub OnStatusChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property OnlineOrderFlag in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property OnlineOrderFlag() As Boolean
            Get
                Return Me._OnlineOrderFlag
            End Get
            Set
                Me.OnOnlineOrderFlagChanging(value)
                Me._OnlineOrderFlag = value
                Me.OnOnlineOrderFlagChanged
                Me.OnPropertyChanged("OnlineOrderFlag")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _OnlineOrderFlag As Boolean
        Partial Private Sub OnOnlineOrderFlagChanging(ByVal value As Boolean)
        End Sub
        Partial Private Sub OnOnlineOrderFlagChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property SalesOrderNumber in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property SalesOrderNumber() As String
            Get
                Return Me._SalesOrderNumber
            End Get
            Set
                Me.OnSalesOrderNumberChanging(value)
                Me._SalesOrderNumber = value
                Me.OnSalesOrderNumberChanged
                Me.OnPropertyChanged("SalesOrderNumber")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _SalesOrderNumber As String
        Partial Private Sub OnSalesOrderNumberChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnSalesOrderNumberChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property PurchaseOrderNumber in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property PurchaseOrderNumber() As String
            Get
                Return Me._PurchaseOrderNumber
            End Get
            Set
                Me.OnPurchaseOrderNumberChanging(value)
                Me._PurchaseOrderNumber = value
                Me.OnPurchaseOrderNumberChanged
                Me.OnPropertyChanged("PurchaseOrderNumber")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _PurchaseOrderNumber As String
        Partial Private Sub OnPurchaseOrderNumberChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnPurchaseOrderNumberChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property AccountNumber in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property AccountNumber() As String
            Get
                Return Me._AccountNumber
            End Get
            Set
                Me.OnAccountNumberChanging(value)
                Me._AccountNumber = value
                Me.OnAccountNumberChanged
                Me.OnPropertyChanged("AccountNumber")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _AccountNumber As String
        Partial Private Sub OnAccountNumberChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnAccountNumberChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property CustomerID in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property CustomerID() As Integer
            Get
                Return Me._CustomerID
            End Get
            Set
                Me.OnCustomerIDChanging(value)
                Me._CustomerID = value
                Me.OnCustomerIDChanged
                Me.OnPropertyChanged("CustomerID")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _CustomerID As Integer
        Partial Private Sub OnCustomerIDChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub OnCustomerIDChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property ShipToAddressID in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ShipToAddressID() As Global.System.Nullable(Of Integer)
            Get
                Return Me._ShipToAddressID
            End Get
            Set
                Me.OnShipToAddressIDChanging(value)
                Me._ShipToAddressID = value
                Me.OnShipToAddressIDChanged
                Me.OnPropertyChanged("ShipToAddressID")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ShipToAddressID As Global.System.Nullable(Of Integer)
        Partial Private Sub OnShipToAddressIDChanging(ByVal value As Global.System.Nullable(Of Integer))
        End Sub
        Partial Private Sub OnShipToAddressIDChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property BillToAddressID in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property BillToAddressID() As Global.System.Nullable(Of Integer)
            Get
                Return Me._BillToAddressID
            End Get
            Set
                Me.OnBillToAddressIDChanging(value)
                Me._BillToAddressID = value
                Me.OnBillToAddressIDChanged
                Me.OnPropertyChanged("BillToAddressID")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _BillToAddressID As Global.System.Nullable(Of Integer)
        Partial Private Sub OnBillToAddressIDChanging(ByVal value As Global.System.Nullable(Of Integer))
        End Sub
        Partial Private Sub OnBillToAddressIDChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property ShipMethod in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ShipMethod() As String
            Get
                Return Me._ShipMethod
            End Get
            Set
                Me.OnShipMethodChanging(value)
                Me._ShipMethod = value
                Me.OnShipMethodChanged
                Me.OnPropertyChanged("ShipMethod")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ShipMethod As String
        Partial Private Sub OnShipMethodChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnShipMethodChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property CreditCardApprovalCode in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property CreditCardApprovalCode() As String
            Get
                Return Me._CreditCardApprovalCode
            End Get
            Set
                Me.OnCreditCardApprovalCodeChanging(value)
                Me._CreditCardApprovalCode = value
                Me.OnCreditCardApprovalCodeChanged
                Me.OnPropertyChanged("CreditCardApprovalCode")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _CreditCardApprovalCode As String
        Partial Private Sub OnCreditCardApprovalCodeChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnCreditCardApprovalCodeChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property SubTotal in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property SubTotal() As Decimal
            Get
                Return Me._SubTotal
            End Get
            Set
                Me.OnSubTotalChanging(value)
                Me._SubTotal = value
                Me.OnSubTotalChanged
                Me.OnPropertyChanged("SubTotal")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _SubTotal As Decimal
        Partial Private Sub OnSubTotalChanging(ByVal value As Decimal)
        End Sub
        Partial Private Sub OnSubTotalChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property TaxAmt in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property TaxAmt() As Decimal
            Get
                Return Me._TaxAmt
            End Get
            Set
                Me.OnTaxAmtChanging(value)
                Me._TaxAmt = value
                Me.OnTaxAmtChanged
                Me.OnPropertyChanged("TaxAmt")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _TaxAmt As Decimal
        Partial Private Sub OnTaxAmtChanging(ByVal value As Decimal)
        End Sub
        Partial Private Sub OnTaxAmtChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Freight in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Freight() As Decimal
            Get
                Return Me._Freight
            End Get
            Set
                Me.OnFreightChanging(value)
                Me._Freight = value
                Me.OnFreightChanged
                Me.OnPropertyChanged("Freight")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Freight As Decimal
        Partial Private Sub OnFreightChanging(ByVal value As Decimal)
        End Sub
        Partial Private Sub OnFreightChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property TotalDue in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property TotalDue() As Decimal
            Get
                Return Me._TotalDue
            End Get
            Set
                Me.OnTotalDueChanging(value)
                Me._TotalDue = value
                Me.OnTotalDueChanged
                Me.OnPropertyChanged("TotalDue")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _TotalDue As Decimal
        Partial Private Sub OnTotalDueChanging(ByVal value As Decimal)
        End Sub
        Partial Private Sub OnTotalDueChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Comment in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Comment() As String
            Get
                Return Me._Comment
            End Get
            Set
                Me.OnCommentChanging(value)
                Me._Comment = value
                Me.OnCommentChanged
                Me.OnPropertyChanged("Comment")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Comment As String
        Partial Private Sub OnCommentChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnCommentChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property rowguid in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property rowguid() As Global.System.Guid
            Get
                Return Me._rowguid
            End Get
            Set
                Me.OnrowguidChanging(value)
                Me._rowguid = value
                Me.OnrowguidChanged
                Me.OnPropertyChanged("rowguid")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _rowguid As Global.System.Guid
        Partial Private Sub OnrowguidChanging(ByVal value As Global.System.Guid)
        End Sub
        Partial Private Sub OnrowguidChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property ModifiedDate in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ModifiedDate() As Date
            Get
                Return Me._ModifiedDate
            End Get
            Set
                Me.OnModifiedDateChanging(value)
                Me._ModifiedDate = value
                Me.OnModifiedDateChanged
                Me.OnPropertyChanged("ModifiedDate")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ModifiedDate As Date
        Partial Private Sub OnModifiedDateChanging(ByVal value As Date)
        End Sub
        Partial Private Sub OnModifiedDateChanged()
        End Sub
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Event PropertyChanged As Global.System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Protected Overridable Sub OnPropertyChanged(ByVal [property] As String)
            If (Not (Me.PropertyChangedEvent) Is Nothing) Then
                RaiseEvent PropertyChanged(Me, New Global.System.ComponentModel.PropertyChangedEventArgs([property]))
            End If
        End Sub
    End Class
End Namespace
