//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17357
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 414
namespace Trin_VstcoreActionsPaneWordCS {
    
    
    /// 
    [Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(0)]
    [global::System.Security.Permissions.PermissionSetAttribute(global::System.Security.Permissions.SecurityAction.Demand, Name="FullTrust")]
    public sealed partial class ThisDocument : Microsoft.Office.Tools.Word.DocumentBase {
        
        internal Microsoft.Office.Tools.ActionsPane ActionsPane;
        
        internal Microsoft.Office.Tools.Word.Bookmark showName;
        
        internal Microsoft.Office.Tools.Word.Bookmark showAddress;
        
        internal Microsoft.Office.Tools.Word.XMLNode SampleNode;
        
        internal Microsoft.Office.Tools.Word.XMLNode SampleInsertNode;
        
        internal Microsoft.Office.Tools.Word.XMLNode InsertMemoToNode;
        
        internal Microsoft.Office.Tools.Word.XMLNode InsertMemoFromNode;
        
        internal Microsoft.Office.Tools.Word.XMLNode InsertMemoSubjectNode;
        
        internal Microsoft.Office.Tools.Word.XMLNode SampleTableNode;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "11.0.0.0")]
        private global::System.Object missing = global::System.Type.Missing;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "11.0.0.0")]
        internal Microsoft.Office.Interop.Word.Application ThisApplication;
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public ThisDocument(global::Microsoft.Office.Tools.Word.Factory factory, global::System.IServiceProvider serviceProvider) : 
                base(factory, serviceProvider, "ThisDocument", "ThisDocument") {
            Globals.Factory = factory;
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "11.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void Initialize() {
            base.Initialize();
            this.ThisApplication = this.GetHostItem<Microsoft.Office.Interop.Word.Application>(typeof(Microsoft.Office.Interop.Word.Application), "Application");
            Globals.ThisDocument = this;
            global::System.Windows.Forms.Application.EnableVisualStyles();
            this.InitializeCachedData();
            this.InitializeControls();
            this.InitializeComponents();
            this.InitializeData();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "11.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void FinishInitialization() {
            this.InternalStartup();
            this.OnStartup();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "11.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void InitializeDataBindings() {
            this.BeginInitialization();
            this.BindToData();
            this.EndInitialization();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "11.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeCachedData() {
            if ((this.DataHost == null)) {
                return;
            }
            if (this.DataHost.IsCacheInitialized) {
                this.DataHost.FillCachedData(this);
            }
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "11.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "11.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BindToData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StartCaching(string MemberName) {
            this.DataHost.StartCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StopCaching(string MemberName) {
            this.DataHost.StopCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool IsCached(string MemberName) {
            return this.DataHost.IsCached(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "11.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BeginInitialization() {
            this.BeginInit();
            this.ActionsPane.BeginInit();
            this.showName.BeginInit();
            this.showAddress.BeginInit();
            this.SampleNode.BeginInit();
            this.SampleInsertNode.BeginInit();
            this.InsertMemoToNode.BeginInit();
            this.InsertMemoFromNode.BeginInit();
            this.InsertMemoSubjectNode.BeginInit();
            this.SampleTableNode.BeginInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "11.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void EndInitialization() {
            this.SampleTableNode.EndInit();
            this.InsertMemoSubjectNode.EndInit();
            this.InsertMemoFromNode.EndInit();
            this.InsertMemoToNode.EndInit();
            this.SampleInsertNode.EndInit();
            this.SampleNode.EndInit();
            this.showAddress.EndInit();
            this.showName.EndInit();
            this.ActionsPane.EndInit();
            this.EndInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "11.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeControls() {
            this.ActionsPane = Globals.Factory.CreateActionsPane(null, null, "ActionsPane", "ActionsPane", this);
            this.showName = Globals.Factory.CreateBookmark(null, null, "showName", "showName", this);
            this.showAddress = Globals.Factory.CreateBookmark(null, null, "showAddress", "showAddress", this);
            this.SampleNode = Globals.Factory.CreateXMLNode(null, null, "/ns0:Sample xmlns:ns0=\'http://schemas.microsoft.com/vsto/samples\'", "SampleNode", this);
            this.SampleInsertNode = Globals.Factory.CreateXMLNode(null, null, "/ns0:Sample/ns0:Insert xmlns:ns0=\'http://schemas.microsoft.com/vsto/samples\'", "SampleInsertNode", this);
            this.InsertMemoToNode = Globals.Factory.CreateXMLNode(null, null, "/ns0:Sample/ns0:Insert/ns0:MemoTo xmlns:ns0=\'http://schemas.microsoft.com/vsto/sa" +
                    "mples\'", "InsertMemoToNode", this);
            this.InsertMemoFromNode = Globals.Factory.CreateXMLNode(null, null, "/ns0:Sample/ns0:Insert/ns0:MemoFrom xmlns:ns0=\'http://schemas.microsoft.com/vsto/" +
                    "samples\'", "InsertMemoFromNode", this);
            this.InsertMemoSubjectNode = Globals.Factory.CreateXMLNode(null, null, "/ns0:Sample/ns0:Insert/ns0:MemoSubject xmlns:ns0=\'http://schemas.microsoft.com/vs" +
                    "to/samples\'", "InsertMemoSubjectNode", this);
            this.SampleTableNode = Globals.Factory.CreateXMLNode(null, null, "/ns0:Sample/ns0:Table xmlns:ns0=\'http://schemas.microsoft.com/vsto/samples\'", "SampleTableNode", this);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "11.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeComponents() {
            ((System.ComponentModel.ISupportInitialize)(this.ActionsPane)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.showName)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.showAddress)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.SampleNode)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.SampleInsertNode)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.InsertMemoToNode)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.InsertMemoFromNode)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.InsertMemoSubjectNode)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.SampleTableNode)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this)).BeginInit();
            // 
            // ThisDocument
            // 
            ((System.ComponentModel.ISupportInitialize)(this.ActionsPane)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.showName)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.showAddress)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.SampleNode)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.SampleInsertNode)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.InsertMemoToNode)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.InsertMemoFromNode)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.InsertMemoSubjectNode)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.SampleTableNode)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this)).EndInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool NeedsFill(string MemberName) {
            return this.DataHost.NeedsFill(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "11.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void OnShutdown() {
            this.SampleTableNode.Dispose();
            this.InsertMemoSubjectNode.Dispose();
            this.InsertMemoFromNode.Dispose();
            this.InsertMemoToNode.Dispose();
            this.SampleInsertNode.Dispose();
            this.SampleNode.Dispose();
            this.showAddress.Dispose();
            this.showName.Dispose();
            this.ActionsPane.Dispose();
            base.OnShutdown();
        }
    }
    
    /// 
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "11.0.0.0")]
    internal sealed partial class Globals {
        
        /// 
        private Globals() {
        }
        
        private static ThisDocument _ThisDocument;
        
        private static global::Microsoft.Office.Tools.Word.Factory _factory;
        
        private static ThisRibbonCollection _ThisRibbonCollection;
        
        internal static ThisDocument ThisDocument {
            get {
                return _ThisDocument;
            }
            set {
                if ((_ThisDocument == null)) {
                    _ThisDocument = value;
                }
                else {
                    throw new System.NotSupportedException();
                }
            }
        }
        
        internal static global::Microsoft.Office.Tools.Word.Factory Factory {
            get {
                return _factory;
            }
            set {
                if ((_factory == null)) {
                    _factory = value;
                }
                else {
                    throw new System.NotSupportedException();
                }
            }
        }
        
        internal static ThisRibbonCollection Ribbons {
            get {
                if ((_ThisRibbonCollection == null)) {
                    _ThisRibbonCollection = new ThisRibbonCollection(_factory.GetRibbonFactory());
                }
                return _ThisRibbonCollection;
            }
        }
    }
    
    /// 
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "11.0.0.0")]
    internal sealed partial class ThisRibbonCollection : Microsoft.Office.Tools.Ribbon.RibbonCollectionBase {
        
        /// 
        internal ThisRibbonCollection(global::Microsoft.Office.Tools.Ribbon.RibbonFactory factory) : 
                base(factory) {
        }
    }
}
